/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as BasicDetailsRouteImport } from './routes/basic-details'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as DriverSetupRouteImport } from './routes/driver-setup'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PassengerChoiceRouteImport } from './routes/passenger-choice'
import { Route as RedeemCoinsRouteImport } from './routes/redeem-coins'
import { Route as ReferEarnRouteImport } from './routes/refer-earn'
import { Route as RoleSelectionRouteImport } from './routes/role-selection'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as AdminAddBusRouteImport } from './routes/admin.add-bus'
import { Route as AdminAddRouteRouteImport } from './routes/admin.add-route'
import { Route as AdminOverviewRouteImport } from './routes/admin.overview'
import { Route as DriverCoinsRouteImport } from './routes/driver.coins'
import { Route as DriverDashboardRouteImport } from './routes/driver.dashboard'
import { Route as DriverLiveTrackingRouteImport } from './routes/driver.live-tracking'
import { Route as DriverProfileRouteImport } from './routes/driver.profile'
import { Route as DriverRecentTripsRouteImport } from './routes/driver.recent-trips'
import { Route as PassengerDashboardRouteImport } from './routes/passenger.dashboard'
import { Route as PassengerHistoryRouteImport } from './routes/passenger.history'
import { Route as PassengerInsideBusRouteImport } from './routes/passenger.inside-bus'
import { Route as PassengerLiveTrackingRouteImport } from './routes/passenger.live-tracking'
import { Route as PassengerProfileRouteImport } from './routes/passenger.profile'
import { Route as PassengerResultsRouteImport } from './routes/passenger.results'
import { Route as PassengerRewardsRouteImport } from './routes/passenger.rewards'
import { Route as PassengerSearchRouteImport } from './routes/passenger.search'
import { Route as AdminEditBusBusIdRouteImport } from './routes/admin.edit-bus.$busId'
import { Route as AdminRouteBusIdRouteImport } from './routes/admin.route.$busId'
import { Route as PassengerRideRideIdRouteImport } from './routes/passenger.ride.$rideId'
import { Route as PassengerRouteBusIdRouteImport } from './routes/passenger.route.$busId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicDetailsRoute = BasicDetailsRouteImport.update({
  id: '/basic-details',
  path: '/basic-details',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverSetupRoute = DriverSetupRouteImport.update({
  id: '/driver-setup',
  path: '/driver-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerChoiceRoute = PassengerChoiceRouteImport.update({
  id: '/passenger-choice',
  path: '/passenger-choice',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemCoinsRoute = RedeemCoinsRouteImport.update({
  id: '/redeem-coins',
  path: '/redeem-coins',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferEarnRoute = ReferEarnRouteImport.update({
  id: '/refer-earn',
  path: '/refer-earn',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleSelectionRoute = RoleSelectionRouteImport.update({
  id: '/role-selection',
  path: '/role-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAddBusRoute = AdminAddBusRouteImport.update({
  id: '/admin/add-bus',
  path: '/admin/add-bus',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAddRouteRoute = AdminAddRouteRouteImport.update({
  id: '/admin/add-route',
  path: '/admin/add-route',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/admin/overview',
  path: '/admin/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverCoinsRoute = DriverCoinsRouteImport.update({
  id: '/driver/coins',
  path: '/driver/coins',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverDashboardRoute = DriverDashboardRouteImport.update({
  id: '/driver/dashboard',
  path: '/driver/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverLiveTrackingRoute = DriverLiveTrackingRouteImport.update({
  id: '/driver/live-tracking',
  path: '/driver/live-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/driver/profile',
  path: '/driver/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRecentTripsRoute = DriverRecentTripsRouteImport.update({
  id: '/driver/recent-trips',
  path: '/driver/recent-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerDashboardRoute = PassengerDashboardRouteImport.update({
  id: '/passenger/dashboard',
  path: '/passenger/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerHistoryRoute = PassengerHistoryRouteImport.update({
  id: '/passenger/history',
  path: '/passenger/history',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerInsideBusRoute = PassengerInsideBusRouteImport.update({
  id: '/passenger/inside-bus',
  path: '/passenger/inside-bus',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerLiveTrackingRoute = PassengerLiveTrackingRouteImport.update({
  id: '/passenger/live-tracking',
  path: '/passenger/live-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerProfileRoute = PassengerProfileRouteImport.update({
  id: '/passenger/profile',
  path: '/passenger/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerResultsRoute = PassengerResultsRouteImport.update({
  id: '/passenger/results',
  path: '/passenger/results',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerRewardsRoute = PassengerRewardsRouteImport.update({
  id: '/passenger/rewards',
  path: '/passenger/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerSearchRoute = PassengerSearchRouteImport.update({
  id: '/passenger/search',
  path: '/passenger/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditBusBusIdRoute = AdminEditBusBusIdRouteImport.update({
  id: '/admin/edit-bus/$busId',
  path: '/admin/edit-bus/$busId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteBusIdRoute = AdminRouteBusIdRouteImport.update({
  id: '/admin/route/$busId',
  path: '/admin/route/$busId',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerRideRideIdRoute = PassengerRideRideIdRouteImport.update({
  id: '/passenger/ride/$rideId',
  path: '/passenger/ride/$rideId',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerRouteBusIdRoute = PassengerRouteBusIdRouteImport.update({
  id: '/passenger/route/$busId',
  path: '/passenger/route/$busId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about-us': typeof AboutUsRoute
  '/basic-details': typeof BasicDetailsRoute
  '/create-account': typeof CreateAccountRoute
  '/driver-setup': typeof DriverSetupRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/passenger-choice': typeof PassengerChoiceRoute
  '/redeem-coins': typeof RedeemCoinsRoute
  '/refer-earn': typeof ReferEarnRoute
  '/role-selection': typeof RoleSelectionRoute
  '/sign-in': typeof SignInRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/add-bus': typeof AdminAddBusRoute
  '/admin/add-route': typeof AdminAddRouteRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/driver/coins': typeof DriverCoinsRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/live-tracking': typeof DriverLiveTrackingRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/recent-trips': typeof DriverRecentTripsRoute
  '/passenger/dashboard': typeof PassengerDashboardRoute
  '/passenger/history': typeof PassengerHistoryRoute
  '/passenger/inside-bus': typeof PassengerInsideBusRoute
  '/passenger/live-tracking': typeof PassengerLiveTrackingRoute
  '/passenger/profile': typeof PassengerProfileRoute
  '/passenger/results': typeof PassengerResultsRoute
  '/passenger/rewards': typeof PassengerRewardsRoute
  '/passenger/search': typeof PassengerSearchRoute
  '/admin/route/$busId': typeof AdminRouteBusIdRoute
  '/passenger/route/$busId': typeof PassengerRouteBusIdRoute
  '/admin/edit-bus/$busId': typeof AdminEditBusBusIdRoute
  '/passenger/ride/$rideId': typeof PassengerRideRideIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about-us': typeof AboutUsRoute
  '/basic-details': typeof BasicDetailsRoute
  '/create-account': typeof CreateAccountRoute
  '/driver-setup': typeof DriverSetupRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/passenger-choice': typeof PassengerChoiceRoute
  '/redeem-coins': typeof RedeemCoinsRoute
  '/refer-earn': typeof ReferEarnRoute
  '/role-selection': typeof RoleSelectionRoute
  '/sign-in': typeof SignInRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/add-bus': typeof AdminAddBusRoute
  '/admin/add-route': typeof AdminAddRouteRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/driver/coins': typeof DriverCoinsRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/live-tracking': typeof DriverLiveTrackingRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/recent-trips': typeof DriverRecentTripsRoute
  '/passenger/dashboard': typeof PassengerDashboardRoute
  '/passenger/history': typeof PassengerHistoryRoute
  '/passenger/inside-bus': typeof PassengerInsideBusRoute
  '/passenger/live-tracking': typeof PassengerLiveTrackingRoute
  '/passenger/profile': typeof PassengerProfileRoute
  '/passenger/results': typeof PassengerResultsRoute
  '/passenger/rewards': typeof PassengerRewardsRoute
  '/passenger/search': typeof PassengerSearchRoute
  '/admin/route/$busId': typeof AdminRouteBusIdRoute
  '/passenger/route/$busId': typeof PassengerRouteBusIdRoute
  '/admin/edit-bus/$busId': typeof AdminEditBusBusIdRoute
  '/passenger/ride/$rideId': typeof PassengerRideRideIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about-us': typeof AboutUsRoute
  '/basic-details': typeof BasicDetailsRoute
  '/create-account': typeof CreateAccountRoute
  '/driver-setup': typeof DriverSetupRoute
  '/feedback': typeof FeedbackRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/passenger-choice': typeof PassengerChoiceRoute
  '/redeem-coins': typeof RedeemCoinsRoute
  '/refer-earn': typeof ReferEarnRoute
  '/role-selection': typeof RoleSelectionRoute
  '/sign-in': typeof SignInRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/add-bus': typeof AdminAddBusRoute
  '/admin/add-route': typeof AdminAddRouteRoute
  '/admin/overview': typeof AdminOverviewRoute
  '/driver/coins': typeof DriverCoinsRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/live-tracking': typeof DriverLiveTrackingRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/recent-trips': typeof DriverRecentTripsRoute
  '/passenger/dashboard': typeof PassengerDashboardRoute
  '/passenger/history': typeof PassengerHistoryRoute
  '/passenger/inside-bus': typeof PassengerInsideBusRoute
  '/passenger/live-tracking': typeof PassengerLiveTrackingRoute
  '/passenger/profile': typeof PassengerProfileRoute
  '/passenger/results': typeof PassengerResultsRoute
  '/passenger/rewards': typeof PassengerRewardsRoute
  '/passenger/search': typeof PassengerSearchRoute
  '/admin/route/$busId': typeof AdminRouteBusIdRoute
  '/passenger/route/$busId': typeof PassengerRouteBusIdRoute
  '/admin/edit-bus/$busId': typeof AdminEditBusBusIdRoute
  '/passenger/ride/$rideId': typeof PassengerRideRideIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about-us'
    | '/basic-details'
    | '/create-account'
    | '/driver-setup'
    | '/feedback'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/passenger-choice'
    | '/redeem-coins'
    | '/refer-earn'
    | '/role-selection'
    | '/sign-in'
    | '/verify-otp'
    | '/admin/add-bus'
    | '/admin/add-route'
    | '/admin/overview'
    | '/driver/coins'
    | '/driver/dashboard'
    | '/driver/live-tracking'
    | '/driver/profile'
    | '/driver/recent-trips'
    | '/passenger/dashboard'
    | '/passenger/history'
    | '/passenger/inside-bus'
    | '/passenger/live-tracking'
    | '/passenger/profile'
    | '/passenger/results'
    | '/passenger/rewards'
    | '/passenger/search'
    | '/admin/route/$busId'
    | '/passenger/route/$busId'
    | '/admin/edit-bus/$busId'
    | '/passenger/ride/$rideId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about-us'
    | '/basic-details'
    | '/create-account'
    | '/driver-setup'
    | '/feedback'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/passenger-choice'
    | '/redeem-coins'
    | '/refer-earn'
    | '/role-selection'
    | '/sign-in'
    | '/verify-otp'
    | '/admin/add-bus'
    | '/admin/add-route'
    | '/admin/overview'
    | '/driver/coins'
    | '/driver/dashboard'
    | '/driver/live-tracking'
    | '/driver/profile'
    | '/driver/recent-trips'
    | '/passenger/dashboard'
    | '/passenger/history'
    | '/passenger/inside-bus'
    | '/passenger/live-tracking'
    | '/passenger/profile'
    | '/passenger/results'
    | '/passenger/rewards'
    | '/passenger/search'
    | '/admin/route/$busId'
    | '/passenger/route/$busId'
    | '/admin/edit-bus/$busId'
    | '/passenger/ride/$rideId'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about-us'
    | '/basic-details'
    | '/create-account'
    | '/driver-setup'
    | '/feedback'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/passenger-choice'
    | '/redeem-coins'
    | '/refer-earn'
    | '/role-selection'
    | '/sign-in'
    | '/verify-otp'
    | '/admin/add-bus'
    | '/admin/add-route'
    | '/admin/overview'
    | '/driver/coins'
    | '/driver/dashboard'
    | '/driver/live-tracking'
    | '/driver/profile'
    | '/driver/recent-trips'
    | '/passenger/dashboard'
    | '/passenger/history'
    | '/passenger/inside-bus'
    | '/passenger/live-tracking'
    | '/passenger/profile'
    | '/passenger/results'
    | '/passenger/rewards'
    | '/passenger/search'
    | '/admin/route/$busId'
    | '/passenger/route/$busId'
    | '/admin/edit-bus/$busId'
    | '/passenger/ride/$rideId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutUsRoute: typeof AboutUsRoute
  BasicDetailsRoute: typeof BasicDetailsRoute
  CreateAccountRoute: typeof CreateAccountRoute
  DriverSetupRoute: typeof DriverSetupRoute
  FeedbackRoute: typeof FeedbackRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  PassengerChoiceRoute: typeof PassengerChoiceRoute
  RedeemCoinsRoute: typeof RedeemCoinsRoute
  ReferEarnRoute: typeof ReferEarnRoute
  RoleSelectionRoute: typeof RoleSelectionRoute
  SignInRoute: typeof SignInRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  AdminAddBusRoute: typeof AdminAddBusRoute
  AdminAddRouteRoute: typeof AdminAddRouteRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  DriverCoinsRoute: typeof DriverCoinsRoute
  DriverDashboardRoute: typeof DriverDashboardRoute
  DriverLiveTrackingRoute: typeof DriverLiveTrackingRoute
  DriverProfileRoute: typeof DriverProfileRoute
  DriverRecentTripsRoute: typeof DriverRecentTripsRoute
  PassengerDashboardRoute: typeof PassengerDashboardRoute
  PassengerHistoryRoute: typeof PassengerHistoryRoute
  PassengerInsideBusRoute: typeof PassengerInsideBusRoute
  PassengerLiveTrackingRoute: typeof PassengerLiveTrackingRoute
  PassengerProfileRoute: typeof PassengerProfileRoute
  PassengerResultsRoute: typeof PassengerResultsRoute
  PassengerRewardsRoute: typeof PassengerRewardsRoute
  PassengerSearchRoute: typeof PassengerSearchRoute
  AdminRouteBusIdRoute: typeof AdminRouteBusIdRoute
  PassengerRouteBusIdRoute: typeof PassengerRouteBusIdRoute
  AdminEditBusBusIdRoute: typeof AdminEditBusBusIdRoute
  PassengerRideRideIdRoute: typeof PassengerRideRideIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic-details': {
      id: '/basic-details'
      path: '/basic-details'
      fullPath: '/basic-details'
      preLoaderRoute: typeof BasicDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-setup': {
      id: '/driver-setup'
      path: '/driver-setup'
      fullPath: '/driver-setup'
      preLoaderRoute: typeof DriverSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger-choice': {
      id: '/passenger-choice'
      path: '/passenger-choice'
      fullPath: '/passenger-choice'
      preLoaderRoute: typeof PassengerChoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem-coins': {
      id: '/redeem-coins'
      path: '/redeem-coins'
      fullPath: '/redeem-coins'
      preLoaderRoute: typeof RedeemCoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer-earn': {
      id: '/refer-earn'
      path: '/refer-earn'
      fullPath: '/refer-earn'
      preLoaderRoute: typeof ReferEarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-selection': {
      id: '/role-selection'
      path: '/role-selection'
      fullPath: '/role-selection'
      preLoaderRoute: typeof RoleSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/add-bus': {
      id: '/admin/add-bus'
      path: '/admin/add-bus'
      fullPath: '/admin/add-bus'
      preLoaderRoute: typeof AdminAddBusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/add-route': {
      id: '/admin/add-route'
      path: '/admin/add-route'
      fullPath: '/admin/add-route'
      preLoaderRoute: typeof AdminAddRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/overview': {
      id: '/admin/overview'
      path: '/admin/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/coins': {
      id: '/driver/coins'
      path: '/driver/coins'
      fullPath: '/driver/coins'
      preLoaderRoute: typeof DriverCoinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/dashboard': {
      id: '/driver/dashboard'
      path: '/driver/dashboard'
      fullPath: '/driver/dashboard'
      preLoaderRoute: typeof DriverDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/live-tracking': {
      id: '/driver/live-tracking'
      path: '/driver/live-tracking'
      fullPath: '/driver/live-tracking'
      preLoaderRoute: typeof DriverLiveTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/profile': {
      id: '/driver/profile'
      path: '/driver/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/recent-trips': {
      id: '/driver/recent-trips'
      path: '/driver/recent-trips'
      fullPath: '/driver/recent-trips'
      preLoaderRoute: typeof DriverRecentTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/dashboard': {
      id: '/passenger/dashboard'
      path: '/passenger/dashboard'
      fullPath: '/passenger/dashboard'
      preLoaderRoute: typeof PassengerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/history': {
      id: '/passenger/history'
      path: '/passenger/history'
      fullPath: '/passenger/history'
      preLoaderRoute: typeof PassengerHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/inside-bus': {
      id: '/passenger/inside-bus'
      path: '/passenger/inside-bus'
      fullPath: '/passenger/inside-bus'
      preLoaderRoute: typeof PassengerInsideBusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/live-tracking': {
      id: '/passenger/live-tracking'
      path: '/passenger/live-tracking'
      fullPath: '/passenger/live-tracking'
      preLoaderRoute: typeof PassengerLiveTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/profile': {
      id: '/passenger/profile'
      path: '/passenger/profile'
      fullPath: '/passenger/profile'
      preLoaderRoute: typeof PassengerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/results': {
      id: '/passenger/results'
      path: '/passenger/results'
      fullPath: '/passenger/results'
      preLoaderRoute: typeof PassengerResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/rewards': {
      id: '/passenger/rewards'
      path: '/passenger/rewards'
      fullPath: '/passenger/rewards'
      preLoaderRoute: typeof PassengerRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/search': {
      id: '/passenger/search'
      path: '/passenger/search'
      fullPath: '/passenger/search'
      preLoaderRoute: typeof PassengerSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/edit-bus/$busId': {
      id: '/admin/edit-bus/$busId'
      path: '/admin/edit-bus/$busId'
      fullPath: '/admin/edit-bus/$busId'
      preLoaderRoute: typeof AdminEditBusBusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/route/$busId': {
      id: '/admin/route/$busId'
      path: '/admin/route/$busId'
      fullPath: '/admin/route/$busId'
      preLoaderRoute: typeof AdminRouteBusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/ride/$rideId': {
      id: '/passenger/ride/$rideId'
      path: '/passenger/ride/$rideId'
      fullPath: '/passenger/ride/$rideId'
      preLoaderRoute: typeof PassengerRideRideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/route/$busId': {
      id: '/passenger/route/$busId'
      path: '/passenger/route/$busId'
      fullPath: '/passenger/route/$busId'
      preLoaderRoute: typeof PassengerRouteBusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutUsRoute: AboutUsRoute,
  BasicDetailsRoute: BasicDetailsRoute,
  CreateAccountRoute: CreateAccountRoute,
  DriverSetupRoute: DriverSetupRoute,
  FeedbackRoute: FeedbackRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  PassengerChoiceRoute: PassengerChoiceRoute,
  RedeemCoinsRoute: RedeemCoinsRoute,
  ReferEarnRoute: ReferEarnRoute,
  RoleSelectionRoute: RoleSelectionRoute,
  SignInRoute: SignInRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  AdminAddBusRoute: AdminAddBusRoute,
  AdminAddRouteRoute: AdminAddRouteRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  DriverCoinsRoute: DriverCoinsRoute,
  DriverDashboardRoute: DriverDashboardRoute,
  DriverLiveTrackingRoute: DriverLiveTrackingRoute,
  DriverProfileRoute: DriverProfileRoute,
  DriverRecentTripsRoute: DriverRecentTripsRoute,
  PassengerDashboardRoute: PassengerDashboardRoute,
  PassengerHistoryRoute: PassengerHistoryRoute,
  PassengerInsideBusRoute: PassengerInsideBusRoute,
  PassengerLiveTrackingRoute: PassengerLiveTrackingRoute,
  PassengerProfileRoute: PassengerProfileRoute,
  PassengerResultsRoute: PassengerResultsRoute,
  PassengerRewardsRoute: PassengerRewardsRoute,
  PassengerSearchRoute: PassengerSearchRoute,
  AdminRouteBusIdRoute: AdminRouteBusIdRoute,
  PassengerRouteBusIdRoute: PassengerRouteBusIdRoute,
  AdminEditBusBusIdRoute: AdminEditBusBusIdRoute,
  PassengerRideRideIdRoute: PassengerRideRideIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
